* Emacs 29 configuration from the README.org file.

** Why use a org file to manage your Emacs configuration?

The main reason is to ease navigation of the configuration file once it becomes longer than the length of the screen.
Mine tend to be several thousand lines long.
Screwing up and down is there a pain.
You can collapse the file tree in org to greatly ease navigation.
You can also set up a table contents with links to specific sites further down in the file.

** A simple approach

I found a simple approach to using an org file as the means of configuring Emacs.
This is possible now because org-mode is built into GNU Emacs.
This approach was not possible when several years ago when I last used a org file to manage my Emacs configuration.

1. You place the following two lines of code in a *init.el* file after you move your existing *init.el* file to a safe place. Include nothing else. Emacs will write some lines of customization during the first boot up of Emacs.

#+BEGIN_SRC markdown
(require 'org)
(org-babel-load-file (expand-file-name "init.org" user-emacs-directory))
#+END_SRC

2. Build your init.org file.
  - Place elisp code in org mode source blocks. Use my wrap-region-with-org-src-block function to warp marked regions of elisp in org-mode source blocks
  - Add org-style headlines
  - Use the my org-toc-generate function to generate a table of contents. They will show up in separate buffer. You will have to copy and paste them into init.org.

#+TOC: headlines
* [[A]]
* [[B]]

* A

* B
